// 下拉族 17 个 JS 常量 + _CUSTOM_SCROLL_CAP（session.py :904-1535 逐字节锚定——
// batch2b.json js 节由 gen-batch2b-anchors.py venv 实跑生成，测试逐字节比对）。
// 行数组 join 形态：模板字面量的转义规则会腐蚀正则/反引号内容，join 保字节精确。

/** native 单选（session.py :904-957） */
export const SELECT_OPTION_JS = [
  "",
  "function(targetText) {",
  "    const element = this;",
  "    if (!element || element.tagName.toLowerCase() !== 'select') {",
  "        return { success: false, error: 'Element is not a <select>' };",
  "    }",
  "    const targetLower = (targetText || '').toLowerCase();",
  "    const options = Array.from(element.options);",
  "    for (const option of options) {",
  "        const textLower = (option.text || '').trim().toLowerCase();",
  "        const valueLower = (option.value || '').toLowerCase();",
  "        if (textLower === targetLower || valueLower === targetLower) {",
  "            const expectedValue = option.value;",
  "            element.focus();",
  "            element.value = expectedValue;",
  "            option.selected = true;",
  "            element.selectedIndex = option.index;",
  "            element.dispatchEvent(new Event('input', { bubbles: true, cancelable: true }));",
  "            element.dispatchEvent(new Event('change', { bubbles: true, cancelable: true }));",
  "            element.blur();",
  "            if (element.value !== expectedValue) {",
  "                return {",
  "                    success: false,",
  "                    error: 'Selection was set but reverted by page framework. The dropdown may require clicking.',",
  "                    selectionReverted: true,",
  "                    targetOption: { text: (option.text || '').trim(), value: expectedValue, index: option.index },",
  "                    availableOptions: options.map(o => ({ text: (o.text || '').trim(), value: o.value })),",
  "                };",
  "            }",
  "            return {",
  "                success: true,",
  // biome-ignore lint/suspicious/noTemplateCurlyInString: 生成产物——常量体含 ${} 是移植的 JS 内容
  "                message: `Selected option: ${(option.text || '').trim()} (value: ${option.value})`,",
  "                value: option.value,",
  "            };",
  "        }",
  "    }",
  "    return {",
  "        success: false,",
  // biome-ignore lint/suspicious/noTemplateCurlyInString: 生成产物——常量体含 ${} 是移植的 JS 内容
  "        error: `Option with text or value '${targetText}' not found in select element`,",
  "        availableOptions: options.map(o => ({ text: (o.text || '').trim(), value: o.value })),",
  "    };",
  "}",
  "",
].join("\n");

/** native 多选整组设置（:958-1027，issue #192） */
export const SELECT_OPTION_MULTI_JS = [
  "",
  "function(targetTexts) {",
  "    const element = this;",
  "    if (!element || element.tagName.toLowerCase() !== 'select') {",
  "        return { success: false, error: 'Element is not a <select>' };",
  "    }",
  "    if (!element.multiple) {",
  "        return { success: false, error: 'Element is not a multi-select (no multiple attribute); pass a single value= instead' };",
  "    }",
  "    if (!Array.isArray(targetTexts) || targetTexts.length === 0) {",
  "        return { success: false, error: 'values must be a non-empty list' };",
  "    }",
  "    const targets = [];",
  '    // Set 去重（review1：普通对象做集合会被原型链污染——"constructor"/"toString"/',
  '    // "__proto__" 等键取到继承值恒 truthy，目标被静默丢弃不进 missed → 漏选仍报',
  "    // success，极端时清空全部选中）。空串目标过滤后 targets 仍须非空，否则",
  '    // 整组 selected=false 会清空既有选中并误报 "Selected 0 options"。',
  "    const seen = new Set();",
  "    for (const t of targetTexts) {",
  "        const k = (t || '').toLowerCase();",
  "        if (k && !seen.has(k)) { seen.add(k); targets.push(k); }",
  "    }",
  "    if (targets.length === 0) {",
  "        return { success: false, error: 'values must be a non-empty list' };",
  "    }",
  "    const options = Array.from(element.options);",
  "    const matches = function(o) {",
  "        const textLower = (o.text || '').trim().toLowerCase();",
  "        const valueLower = (o.value || '').toLowerCase();",
  "        return targets.indexOf(textLower) !== -1 || targets.indexOf(valueLower) !== -1;",
  "    };",
  "    const missed = targets.filter(function(t) {",
  "        return !options.some(function(o) {",
  "            return (o.text || '').trim().toLowerCase() === t || (o.value || '').toLowerCase() === t;",
  "        });",
  "    });",
  "    if (missed.length > 0) {",
  "        return {",
  "            success: false,",
  "            error: 'Options not found: ' + missed.join(', '),",
  "            missed: missed,",
  "            availableOptions: options.map(o => ({ text: (o.text || '').trim(), value: o.value })),",
  "        };",
  "    }",
  "    const matched = options.filter(matches);",
  "    element.focus();",
  "    for (const o of options) o.selected = matches(o);",
  "    element.dispatchEvent(new Event('input', { bubbles: true, cancelable: true }));",
  "    element.dispatchEvent(new Event('change', { bubbles: true, cancelable: true }));",
  "    element.blur();",
  "    const selectedNow = options.filter(o => o.selected);",
  "    if (!(matched.every(o => o.selected) && selectedNow.length === matched.length)) {",
  "        return {",
  "            success: false,",
  "            error: 'Selection was set but reverted by page framework.',",
  "            availableOptions: options.map(o => ({ text: (o.text || '').trim(), value: o.value, selected: o.selected })),",
  "        };",
  "    }",
  "    return {",
  "        success: true,",
  "        message: 'Selected ' + matched.length + ' options: ' + matched.map(o => (o.text || '').trim()).join(', '),",
  "        values: matched.map(o => o.value),",
  "    };",
  "}",
  "",
].join("\n");

/** 框架回退后的点击回退（:1028-1054） */
export const SELECT_OPTION_CLICK_FALLBACK_JS = [
  "",
  "function(optionIndex) {",
  "    const select = this;",
  "    if (!select || select.tagName.toLowerCase() !== 'select') return { success: false, error: 'Not a select element' };",
  "    const option = select.options[optionIndex];",
  // biome-ignore lint/suspicious/noTemplateCurlyInString: 生成产物——常量体含 ${} 是移植的 JS 内容
  "    if (!option) return { success: false, error: `Option not found at index ${optionIndex}` };",
  "    select.focus();",
  "    select.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true, view: window }));",
  "    select.selectedIndex = optionIndex;",
  "    option.selected = true;",
  "    option.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true, view: window }));",
  "    select.dispatchEvent(new MouseEvent('mouseup', { bubbles: true, cancelable: true, view: window }));",
  "    select.dispatchEvent(new Event('change', { bubbles: true, cancelable: true }));",
  "    select.blur();",
  "    if (select.value === option.value || select.selectedIndex === optionIndex) {",
  // biome-ignore lint/suspicious/noTemplateCurlyInString: 生成产物——常量体含 ${} 是移植的 JS 内容
  "        return { success: true, message: `Selected via click fallback: ${(option.text || '').trim()}`, value: option.value };",
  "    }",
  "    return { success: false, error: 'Click fallback also failed - framework may block all programmatic selection', finalValue: select.value, expectedValue: option.value };",
  "}",
  "",
].join("\n");

/** ARIA menu/listbox 选项枚举（:1055-1082） */
export const ARIA_OPTIONS_JS = [
  "",
  "function() {",
  "    const root = this;",
  "    const role = root.getAttribute('role');",
  "    const isAriaContainer = ['listbox', 'menu', 'menubar', 'tree', 'grid'].indexOf(role) !== -1;",
  '    const hasAriaOptions = !!root.querySelector(\'[role="option"],[role="menuitem"]\');',
  "    if (!isAriaContainer && !hasAriaOptions) return null;",
  '    const all = Array.from(root.querySelectorAll(\'[role="menuitem"],[role="option"]\'));',
  "    const capped = all.slice(0, 200);",
  "    const mapped = capped.map(function(n) {",
  "        return {",
  "            text: (n.textContent || '').trim(),",
  "            value: n.getAttribute('data-value') || n.getAttribute('value') || (n.textContent || '').trim(),",
  "            selected: n.getAttribute('aria-selected') === 'true' || n.classList.contains('selected') || n.classList.contains('active'),",
  "        };",
  "    });",
  "    if (all.length > 200) {",
  "        mapped.push({text: '... (showing 200 of ' + all.length + ', use scroll/search_page for more)', value: '', selected: false});",
  "    }",
  "    return mapped;",
  "}",
  "",
].join("\n");

/** custom class 下拉枚举（Semantic UI，:1083-1108） */
export const CUSTOM_CLASS_OPTIONS_JS = [
  "",
  "function() {",
  "    const root = this;",
  "    if (!(root.classList.contains('dropdown') || root.classList.contains('ui'))) {",
  "        return null;",
  "    }",
  "    const all = Array.from(root.querySelectorAll('.item, .option, [data-value]'));",
  "    const capped = all.slice(0, 200);",
  "    const mapped = capped.map(function(n) {",
  "        return {",
  "            text: (n.textContent || '').trim(),",
  "            value: n.getAttribute('data-value') || n.getAttribute('value') || (n.textContent || '').trim(),",
  "            selected: n.classList.contains('selected') || n.classList.contains('active'),",
  "        };",
  "    });",
  "    if (all.length > 200) {",
  "        mapped.push({text: '... (showing 200 of ' + all.length + ', use scroll/search_page for more)', value: '', selected: false});",
  "    }",
  "    return mapped;",
  "}",
  "",
].join("\n");

/** combobox aria-controls listbox 读取（:1109-1137） */
export const COMBOBOX_OPTIONS_JS = [
  "",
  "function() {",
  "    const combo = this;",
  "    const controlsId = combo.getAttribute('aria-controls') || combo.getAttribute('aria-owns');",
  "    if (!controlsId) return {options: [], listboxFound: false, error: 'no aria-controls/aria-owns'};",
  "    const listbox = document.getElementById(controlsId);",
  "    if (!listbox) return {options: [], listboxFound: false, error: 'listbox not found'};",
  "    const all = Array.from(listbox.querySelectorAll('[role=\"option\"], li'));",
  "    const capped = all.slice(0, 200);",
  "    const mapped = capped.map(function(n) {",
  "        return {",
  "            text: (n.textContent || '').trim(),",
  "            value: n.getAttribute('data-value') || n.getAttribute('value') || (n.textContent || '').trim(),",
  "            selected: n.getAttribute('aria-selected') === 'true' || n.classList.contains('selected'),",
  "        };",
  "    });",
  "    if (all.length > 200) {",
  "        mapped.push({text: '... (showing 200 of ' + all.length + ', use scroll/search_page for more)', value: '', selected: false});",
  "    }",
  "    return {options: mapped, listboxFound: true};",
  "}",
  "",
].join("\n");

/** 子树 BFS 搜下拉并原地读（:1138-1177） */
export const SUBTREE_SEARCH_JS = [
  "",
  "function(maxDepth) {",
  "    const start = this;",
  "    function readAria(el) {",
  '        const ns = Array.from(el.querySelectorAll(\'[role="menuitem"],[role="option"]\')).slice(0, 200);',
  "        return ns.map(function(n) {",
  "            return {text: (n.textContent||'').trim(), value: n.getAttribute('data-value')||n.getAttribute('value')||(n.textContent||'').trim(), selected: n.getAttribute('aria-selected')==='true'||n.classList.contains('selected')};",
  "        });",
  "    }",
  "    function readCustom(el) {",
  "        const ns = Array.from(el.querySelectorAll('.item, .option, [data-value]')).slice(0, 200);",
  "        return ns.map(function(n) {",
  "            return {text: (n.textContent||'').trim(), value: n.getAttribute('data-value')||n.getAttribute('value')||(n.textContent||'').trim(), selected: n.classList.contains('selected')||n.classList.contains('active')};",
  "        });",
  "    }",
  "    function classify(el) {",
  "        if (el.querySelector('[role=\"option\"],[role=\"menuitem\"]')) return 'aria';",
  "        if ((el.classList.contains('dropdown') || el.classList.contains('ui')) && el.querySelector('.item,.option,[data-value]')) return 'custom';",
  "        return null;",
  "    }",
  "    var queue = [[start, 0]];",
  "    while (queue.length) {",
  "        var pair = queue.shift(); var el = pair[0]; var d = pair[1];",
  "        if (d > 0) {",
  "            var t = classify(el);",
  "            if (t === 'aria') return {options: readAria(el), source: 'child-depth-' + d};",
  "            if (t === 'custom') return {options: readCustom(el), source: 'child-depth-' + d};",
  "        }",
  "        if (d < maxDepth) {",
  "            for (var i = 0; i < el.children.length; i++) queue.push([el.children[i], d + 1]);",
  "        }",
  "    }",
  "    return {options: [], source: null};",
  "}",
  "",
].join("\n");

/** ARIA option 写入（:1178-1235） */
export const SET_ARIA_JS = [
  "",
  "function(targetText) {",
  "    const root = this;",
  "    const role = root.getAttribute('role');",
  "    const isAriaContainer = ['listbox', 'menu', 'menubar', 'tree', 'grid'].indexOf(role) !== -1;",
  '    const hasAriaOptions = !!root.querySelector(\'[role="option"],[role="menuitem"]\');',
  "    if (!isAriaContainer && !hasAriaOptions) {",
  "        return { success: false, error: 'Element is not an ARIA listbox/menu' };",
  "    }",
  '    const all = Array.from(root.querySelectorAll(\'[role="menuitem"],[role="option"]\'));',
  "    const availableOptions = all.map(function(n) {",
  "        return { text: (n.textContent || '').trim(), value: n.getAttribute('data-value') || n.getAttribute('value') || (n.textContent || '').trim() };",
  "    });",
  "    const targetLower = (targetText || '').toLowerCase();",
  "    for (const item of all) {",
  "        const textLower = (item.textContent || '').trim().toLowerCase();",
  "        const valLower = (item.getAttribute('data-value') || item.getAttribute('value') || '').toLowerCase();",
  "        if (textLower === targetLower || valLower === targetLower) {",
  "            root.dispatchEvent(new Event('focus', { bubbles: true, cancelable: true }));",
  "            all.forEach(function(o) {",
  "                o.setAttribute('aria-selected', 'false');",
  "                o.classList.remove('selected');",
  "                o.classList.remove('active');",
  "            });",
  "            item.setAttribute('aria-selected', 'true');",
  "            item.classList.add('selected');",
  "            item.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true, view: window }));",
  "            item.click();",
  "            item.dispatchEvent(new MouseEvent('mouseup', { bubbles: true, cancelable: true, view: window }));",
  "            root.dispatchEvent(new Event('change', { bubbles: true, cancelable: true }));",
  "            const stuck = item.getAttribute('aria-selected') === 'true' || item.classList.contains('selected') || item.classList.contains('active');",
  "            const chosenValue = item.getAttribute('data-value') || item.getAttribute('value') || (item.textContent || '').trim();",
  "            if (!stuck) {",
  "                return {",
  "                    success: false,",
  "                    error: 'Selection was set but not retained. The dropdown may require a different interaction.',",
  "                    targetOption: { text: (item.textContent || '').trim(), value: chosenValue },",
  "                    availableOptions: availableOptions,",
  "                };",
  "            }",
  "            return {",
  "                success: true,",
  // biome-ignore lint/suspicious/noTemplateCurlyInString: 生成产物——常量体含 ${} 是移植的 JS 内容
  "                message: `Selected option: ${(item.textContent || '').trim()} (value: ${chosenValue})`,",
  "                value: chosenValue,",
  "            };",
  "        }",
  "    }",
  "    return {",
  "        success: false,",
  // biome-ignore lint/suspicious/noTemplateCurlyInString: 生成产物——常量体含 ${} 是移植的 JS 内容
  "        error: `Option with text or value '${targetText}' not found in ARIA listbox/menu`,",
  "        availableOptions: availableOptions,",
  "    };",
  "}",
  "",
].join("\n");

/** custom option 写入（:1236-1286） */
export const SET_CUSTOM_JS = [
  "",
  "function(targetText) {",
  "    const root = this;",
  "    if (!(root.classList.contains('dropdown') || root.classList.contains('ui'))) {",
  "        return { success: false, error: 'Element is not a custom-class dropdown' };",
  "    }",
  "    const all = Array.from(root.querySelectorAll('.item, .option, [data-value]'));",
  "    const availableOptions = all.map(function(n) {",
  "        return { text: (n.textContent || '').trim(), value: n.getAttribute('data-value') || n.getAttribute('value') || (n.textContent || '').trim() };",
  "    });",
  "    const targetLower = (targetText || '').toLowerCase();",
  "    for (const item of all) {",
  "        const textLower = (item.textContent || '').trim().toLowerCase();",
  "        const valLower = (item.getAttribute('data-value') || item.getAttribute('value') || '').toLowerCase();",
  "        if (textLower === targetLower || valLower === targetLower) {",
  "            root.dispatchEvent(new Event('focus', { bubbles: true, cancelable: true }));",
  "            all.forEach(function(o) { o.classList.remove('selected'); o.classList.remove('active'); });",
  "            item.classList.add('selected');",
  "            item.classList.add('active');",
  "            item.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true, view: window }));",
  "            item.click();",
  "            item.dispatchEvent(new MouseEvent('mouseup', { bubbles: true, cancelable: true, view: window }));",
  "            root.dispatchEvent(new Event('change', { bubbles: true, cancelable: true }));",
  "            const stuck = item.classList.contains('selected') || item.classList.contains('active');",
  "            const chosenValue = item.getAttribute('data-value') || item.getAttribute('value') || (item.textContent || '').trim();",
  "            if (!stuck) {",
  "                return {",
  "                    success: false,",
  "                    error: 'Selection was set but not retained. The dropdown may require a different interaction.',",
  "                    targetOption: { text: (item.textContent || '').trim(), value: chosenValue },",
  "                    availableOptions: availableOptions,",
  "                };",
  "            }",
  "            return {",
  "                success: true,",
  // biome-ignore lint/suspicious/noTemplateCurlyInString: 生成产物——常量体含 ${} 是移植的 JS 内容
  "                message: `Selected option: ${(item.textContent || '').trim()} (value: ${chosenValue})`,",
  "                value: chosenValue,",
  "            };",
  "        }",
  "    }",
  "    return {",
  "        success: false,",
  // biome-ignore lint/suspicious/noTemplateCurlyInString: 生成产物——常量体含 ${} 是移植的 JS 内容
  "        error: `Option with text or value '${targetText}' not found in custom dropdown`,",
  "        availableOptions: availableOptions,",
  "    };",
  "}",
  "",
].join("\n");

/** combobox listbox 定位（returnByValue=False，:1287-1298） */
export const COMBOBOX_LISTBOX_ID_JS = [
  "",
  "function() {",
  "    const combo = this;",
  "    const controlsId = combo.getAttribute('aria-controls') || combo.getAttribute('aria-owns');",
  "    if (!controlsId) return null;",
  "    return document.getElementById(controlsId);",
  "}",
  "",
].join("\n");

/** combobox listbox 写入（:1299-1346） */
export const SET_COMBOBOX_OPTION_JS = [
  "",
  "function(targetText) {",
  "    const listbox = this;",
  "    const all = Array.from(listbox.querySelectorAll('[role=\"option\"], li'));",
  "    const availableOptions = all.map(function(n) {",
  "        return { text: (n.textContent || '').trim(), value: n.getAttribute('data-value') || n.getAttribute('value') || (n.textContent || '').trim() };",
  "    });",
  "    if (!all.length) {",
  "        return { success: false, error: 'combobox listbox has no [role=option] or li', availableOptions: [] };",
  "    }",
  "    const targetLower = (targetText || '').toLowerCase();",
  "    for (const item of all) {",
  "        const textLower = (item.textContent || '').trim().toLowerCase();",
  "        const valLower = (item.getAttribute('data-value') || item.getAttribute('value') || '').toLowerCase();",
  "        if (textLower === targetLower || valLower === targetLower) {",
  "            all.forEach(function(o) { o.setAttribute('aria-selected', 'false'); });",
  "            item.setAttribute('aria-selected', 'true');",
  "            item.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true, view: window }));",
  "            item.click();",
  "            item.dispatchEvent(new MouseEvent('mouseup', { bubbles: true, cancelable: true, view: window }));",
  "            const stuck = item.getAttribute('aria-selected') === 'true';",
  "            const chosenValue = item.getAttribute('data-value') || item.getAttribute('value') || (item.textContent || '').trim();",
  "            if (!stuck) {",
  "                return {",
  "                    success: false,",
  "                    error: 'Combobox selection was set but not retained.',",
  "                    targetOption: { text: (item.textContent || '').trim(), value: chosenValue },",
  "                    availableOptions: availableOptions,",
  "                };",
  "            }",
  "            return {",
  "                success: true,",
  // biome-ignore lint/suspicious/noTemplateCurlyInString: 生成产物——常量体含 ${} 是移植的 JS 内容
  "                message: `Selected option: ${(item.textContent || '').trim()} (value: ${chosenValue})`,",
  "                value: chosenValue,",
  "            };",
  "        }",
  "    }",
  "    return {",
  "        success: false,",
  // biome-ignore lint/suspicious/noTemplateCurlyInString: 生成产物——常量体含 ${} 是移植的 JS 内容
  "        error: `Option with text or value '${targetText}' not found in combobox listbox`,",
  "        availableOptions: availableOptions,",
  "    };",
  "}",
  "",
].join("\n");

/** 子代下拉定位（ objectId 形态，:1347-1378） */
export const SUBTREE_LOCATE_JS = [
  "",
  "function(maxDepth) {",
  "    const start = this;",
  "    function classify(el) {",
  "        if (el.querySelector('[role=\"option\"],[role=\"menuitem\"]')) return 'aria';",
  "        if ((el.classList.contains('dropdown') || el.classList.contains('ui')) && el.querySelector('.item,.option,[data-value]')) return 'custom';",
  "        return null;",
  "    }",
  "    var queue = [[start, 0]];",
  "    while (queue.length) {",
  "        var pair = queue.shift(); var el = pair[0]; var d = pair[1];",
  "        if (d > 0) {",
  "            var t = classify(el);",
  "            if (t) return { found: true, type: t, node: el, depth: d };",
  "        }",
  "        if (d < maxDepth) {",
  "            for (var i = 0; i < el.children.length; i++) queue.push([el.children[i], d + 1]);",
  "        }",
  "    }",
  "    return { found: false, type: null, node: null };",
  "}",
  "",
].join("\n");

/** 展开点击目标解析（最外层 select-ish 祖先，:1379-1403） */
export const EFFECTIVE_CLICK_TARGET_JS = [
  "",
  "function() {",
  "    let node = this.parentElement;",
  "    let best = null;",
  "    for (let i = 0; i < 4 && node; i++, node = node.parentElement) {",
  "        const cls = (typeof node.className === 'string') ? node.className : '';",
  "        const role = node.getAttribute ? node.getAttribute('role') : null;",
  "        if (/(select|dropdown|combobox|picker)/i.test(cls) || role === 'combobox'",
  "            || (node.dataset && node.dataset.component)) {",
  "            best = node;",
  "        }",
  "    }",
  "    return best || this;",
  "}",
  "",
].join("\n");

/** 自定义下拉 list 发现（:1404-1466） */
export const CUSTOM_LISTBOX_DISCOVER_JS = [
  "",
  "function() {",
  "    const trigger = this;",
  '    const OPTION_SEL = \'[role="option"],[role="menuitem"],li,[data-value],.item,.option,[title]\';',
  '    const ROLE_CONT = \'[role="listbox"],[role="menu"],[role="menubar"],[role="tree"],[role="grid"]\';',
  '    const GEN_CONT = ROLE_CONT + \',ul,[class*="list"],[class*="option"],[class*="menu"],[class*="portal"],[class*="popover"],[class*="dropdown"]\';',
  "",
  "    function visible(el) {",
  "        const cs = getComputedStyle(el);",
  "        if (cs.display === 'none' || cs.visibility === 'hidden' || Number(cs.opacity) === 0) return false;",
  "        const r = el.getBoundingClientRect();",
  "        return r.width > 0 || r.height > 0;",
  "    }",
  "    function isOptionList(el) {",
  "        if (!el || !visible(el)) return false;",
  "        return el.querySelectorAll(OPTION_SEL).length >= 2;",
  "    }",
  "    function searchScope(root) {",
  "        if (!root) return null;",
  "        const roleFirst = Array.from(root.querySelectorAll(ROLE_CONT)).filter(isOptionList);",
  "        if (roleFirst.length) return roleFirst[0];",
  "        if (root !== trigger && isOptionList(root)) return root;",
  "        const generic = Array.from(root.querySelectorAll(GEN_CONT)).filter(isOptionList);",
  "        return generic.length ? generic[0] : null;",
  "    }",
  "",
  "    const cid = trigger.getAttribute('aria-controls') || trigger.getAttribute('aria-owns');",
  "    if (cid) { const lb = document.getElementById(cid); if (lb && isOptionList(lb)) return lb; }",
  "",
  "    const scopes = [];",
  "    if (trigger.parentElement) scopes.push(trigger.parentElement);",
  "    const wrapper = trigger.parentElement",
  '        ? trigger.parentElement.closest(\'[class*="select"],[class*="dropdown"],[class*="combobox"],[class*="picker"],[data-component]\')',
  "        : null;",
  "    if (wrapper && scopes.indexOf(wrapper) === -1) scopes.push(wrapper);",
  "    if (wrapper && wrapper.parentElement && scopes.indexOf(wrapper.parentElement) === -1)",
  "        scopes.push(wrapper.parentElement);",
  "    for (const sc of scopes) { const f = searchScope(sc); if (f) return f; }",
  "",
  "    const trect = trigger.getBoundingClientRect();",
  "    function edgeDist(r) {",
  "        const dx = Math.max(trect.left - r.right, r.left - trect.right, 0);",
  "        const dy = Math.max(trect.top - r.bottom, r.top - trect.bottom, 0);",
  "        return Math.hypot(dx, dy);",
  "    }",
  "    function pickFrom(sel) {",
  "        let best = null, bestD = Infinity;",
  "        const cands = document.querySelectorAll(sel);",
  "        for (let i = 0; i < cands.length; i++) {",
  "            const c = cands[i];",
  "            if (!isOptionList(c)) continue;",
  "            const d = edgeDist(c.getBoundingClientRect());",
  "            if (d < bestD) { bestD = d; best = c; }",
  "        }",
  "        return best;",
  "    }",
  "    return pickFrom(ROLE_CONT) || pickFrom(GEN_CONT);",
  "}",
  "",
].join("\n");

/** 开态 options 读取（:1467-1496） */
export const CUSTOM_OPEN_OPTIONS_JS = [
  "",
  "function() {",
  "    const root = this;",
  '    const GEN_SEL = \'[role="option"],[role="menuitem"],li,[data-value],.item,.option,[title]\';',
  "    function readOne(n) {",
  "        const text = (n.textContent || '').replace(/\\s+/g, ' ').trim();",
  "        const value = n.getAttribute('data-value') || n.getAttribute('value')",
  "                      || n.getAttribute('title') || text;",
  "        const selected = n.getAttribute('aria-selected') === 'true'",
  "                         || n.classList.contains('selected')",
  "                         || n.classList.contains('active')",
  "                         || n.classList.contains('checked');",
  "        return { text: text, value: value, selected: selected };",
  "    }",
  '    const roleOpts = root.querySelectorAll(\'[role="option"],[role="menuitem"]\');',
  "    const pool = roleOpts.length ? roleOpts : root.querySelectorAll(GEN_SEL);",
  "    const all = Array.from(pool);",
  "    const total = all.length;",
  "    const capped = all.slice(0, 200);",
  "    const mapped = capped.map(readOne);",
  "    if (total > 200) {",
  "        mapped.push({ text: '... (showing 200 of ' + total + ', use scroll/search_page for more)', value: '', selected: false });",
  "    }",
  "    return mapped;",
  "}",
  "",
].join("\n");

/** list 上找匹配 option（精确→包含，:1497-1521） */
export const CUSTOM_FIND_OPTION_JS = [
  "",
  "function(targetText) {",
  "    const root = this;",
  '    const GEN_SEL = \'[role="option"],[role="menuitem"],li,[data-value],.item,.option,[title]\';',
  "    function textOf(n) { return (n.textContent || '').replace(/\\s+/g, ' ').trim(); }",
  "    function valueOf(n) {",
  "        return n.getAttribute('data-value') || n.getAttribute('value') || n.getAttribute('title') || '';",
  "    }",
  '    const roleOpts = root.querySelectorAll(\'[role="option"],[role="menuitem"]\');',
  "    const all = roleOpts.length ? roleOpts : root.querySelectorAll(GEN_SEL);",
  "    const tl = (targetText || '').toLowerCase();",
  "    for (const n of all) {",
  "        if (textOf(n).toLowerCase() === tl || valueOf(n).toLowerCase() === tl) return n;",
  "    }",
  "    if (tl.length >= 2) {",
  "        for (const n of all) {",
  "            if (textOf(n).toLowerCase().indexOf(tl) !== -1) return n;",
  "        }",
  "    }",
  "    return null;",
  "}",
  "",
].join("\n");

/** listbox 滚一页（虚拟化，:1522-1534） */
export const SCROLL_LISTBOX_JS = [
  "",
  "function() {",
  "    const el = this;",
  "    if (el.scrollHeight <= el.clientHeight + 2) return false;",
  "    const before = el.scrollTop;",
  "    el.scrollTop = before + el.clientHeight;",
  "    if (el.scrollTop === before) return false;",
  "    el.dispatchEvent(new Event('scroll', { bubbles: true }));",
  "    return true;",
  "}",
  "",
].join("\n");

/** 虚拟化滚动页数上限（:1535） */
export const CUSTOM_SCROLL_CAP = 10;
