// 网格四通道 JS 体（batch2c.json js 节逐字节锚定——gen-batch2c-anchors.py venv
// 实跑生成）。行数组 join 形态：模板字面量转义会腐蚀正则与 ${ 内容。

/** 表格行提取核心（actions.py :540-577 段）——legacy/DOM 两通道共用前缀 */
export const TABLE_ROWS_CORE_JS = [
  "",
  "function _gridIsTotalLabel(s) {",
  "    var t = s.toLowerCase().trim();",
  "    // review2#1：'subtotal' 必须与 '小计' 对称——英文小计行不挪出 rows 会被",
  "    // column_sums 双计（Python 侧 _GRID_FOOTER_SKIP_LABELS 挪进 footer 后",
  "    // 按 'subtotal' 跳过比对）。",
  "    return t === 'total' || t === 'totals' || t === 'grand total'",
  "        || t === 'subtotal' || t === '合计' || t === '总计' || t === '小计';",
  "}",
  "function _gridReadRow(tr, heads, p) {",
  "    var cells = tr.querySelectorAll('td,th');",
  "    var row = {}, col = 0;",
  "    for (var c = 0; c < cells.length; c++) {",
  "        var key = (col < heads.length && heads[col]) ? heads[col] : ('col' + col);",
  "        // 注意：fields 过滤只跳过取值，列游标照常推进（被过滤的列仍占位）。",
  "        if (!(p.fields && p.fields.length && p.fields.indexOf(key) < 0)) {",
  "            row[key] = (cells[c].innerText || cells[c].textContent || '').trim();",
  "        }",
  "        // review#2：colspan 折算——合计行常见 <th colspan=N> 形态，按格索引",
  "        // 配对会把数值格绑到错误表头（假 ✗ 或相邻列合计恰等时假 ✓）。",
  "        col += (cells[c].colSpan || 1);",
  "    }",
  "    return row;",
  "}",
  "function _gridReadTable(root, heads, p) {",
  "    var rows = [], footer = [];",
  "    var trs = root.querySelectorAll('tbody tr');",
  "    for (var k = 0; k < trs.length; k++) {",
  "        if (!trs[k].querySelectorAll('td').length) { continue; }",
  "        // review#3：判定取首格（td,th）——合计标签写在 <th> 时首 td 是数值，",
  "        // 漏检会让 Total 行留在 rows 里被双计。",
  "        var cell0 = trs[k].querySelector('td,th');",
  "        var first = (cell0.innerText || cell0.textContent || '').trim();",
  "        if (_gridIsTotalLabel(first)) { footer.push(_gridReadRow(trs[k], heads, p)); continue; }",
  "        rows.push(_gridReadRow(trs[k], heads, p));",
  "    }",
  "    var ftrs = root.querySelectorAll('tfoot tr');",
  "    for (var f = 0; f < ftrs.length; f++) {",
  "        var fr = _gridReadRow(ftrs[f], heads, p);",
  "        if (Object.keys(fr).length) { footer.push(fr); }",
  "    }",
  "    return { rows: rows, footer: footer };",
  "}",
  "",
].join("\n");

/** legacy ExtJS 网格读取（:578-627） */
export const LEGACY_GRID_READ_JS = [
  "",
  "function _gridIsTotalLabel(s) {",
  "    var t = s.toLowerCase().trim();",
  "    // review2#1：'subtotal' 必须与 '小计' 对称——英文小计行不挪出 rows 会被",
  "    // column_sums 双计（Python 侧 _GRID_FOOTER_SKIP_LABELS 挪进 footer 后",
  "    // 按 'subtotal' 跳过比对）。",
  "    return t === 'total' || t === 'totals' || t === 'grand total'",
  "        || t === 'subtotal' || t === '合计' || t === '总计' || t === '小计';",
  "}",
  "function _gridReadRow(tr, heads, p) {",
  "    var cells = tr.querySelectorAll('td,th');",
  "    var row = {}, col = 0;",
  "    for (var c = 0; c < cells.length; c++) {",
  "        var key = (col < heads.length && heads[col]) ? heads[col] : ('col' + col);",
  "        // 注意：fields 过滤只跳过取值，列游标照常推进（被过滤的列仍占位）。",
  "        if (!(p.fields && p.fields.length && p.fields.indexOf(key) < 0)) {",
  "            row[key] = (cells[c].innerText || cells[c].textContent || '').trim();",
  "        }",
  "        // review#2：colspan 折算——合计行常见 <th colspan=N> 形态，按格索引",
  "        // 配对会把数值格绑到错误表头（假 ✗ 或相邻列合计恰等时假 ✓）。",
  "        col += (cells[c].colSpan || 1);",
  "    }",
  "    return row;",
  "}",
  "function _gridReadTable(root, heads, p) {",
  "    var rows = [], footer = [];",
  "    var trs = root.querySelectorAll('tbody tr');",
  "    for (var k = 0; k < trs.length; k++) {",
  "        if (!trs[k].querySelectorAll('td').length) { continue; }",
  "        // review#3：判定取首格（td,th）——合计标签写在 <th> 时首 td 是数值，",
  "        // 漏检会让 Total 行留在 rows 里被双计。",
  "        var cell0 = trs[k].querySelector('td,th');",
  "        var first = (cell0.innerText || cell0.textContent || '').trim();",
  "        if (_gridIsTotalLabel(first)) { footer.push(_gridReadRow(trs[k], heads, p)); continue; }",
  "        rows.push(_gridReadRow(trs[k], heads, p));",
  "    }",
  "    var ftrs = root.querySelectorAll('tfoot tr');",
  "    for (var f = 0; f < ftrs.length; f++) {",
  "        var fr = _gridReadRow(ftrs[f], heads, p);",
  "        if (Object.keys(fr).length) { footer.push(fr); }",
  "    }",
  "    return { rows: rows, footer: footer };",
  "}",
  "",
  "return (async function(){",
  "    var p = a[0];",
  "    try {",
  "        var objs = [];",
  "        for (var k in window) {",
  "            var v;",
  "            try { v = window[k]; } catch (e) { continue; }",
  "            if (/GridJsObject$/.test(k) && v && typeof v === 'object' && v.url) { objs.push(v); }",
  "        }",
  "        if (!objs.length) { return JSON.stringify({channel_error: 'no-legacy-grid'}); }",
  "        var g = objs[0];",
  "        var fk = '';",
  "        var fkEl = document.querySelector('input[name=form_key]');",
  "        if (fkEl) { fk = fkEl.value; }",
  "        else if (typeof window.FORM_KEY === 'string') { fk = window.FORM_KEY; }",
  "        var parts = ['isAjax=1', 'limit=' + (p.paging ? p.paging.pageSize : 200),",
  "            (g.pageVar || 'page') + '=' + (p.paging ? p.paging.current : 1)];",
  "        if (fk) { parts.push('form_key=' + encodeURIComponent(fk)); }",
  "        if (p.sorting && p.sorting.field) {",
  "            parts.push((g.sortVar || 'sort') + '=' + encodeURIComponent(p.sorting.field));",
  "            parts.push((g.dirVar || 'dir') + '=' + (p.sorting.direction || 'asc'));",
  "        }",
  "        var r = await fetch(g.url + '?' + parts.join('&'), {",
  "            headers: { 'X-Requested-With': 'XMLHttpRequest' }, credentials: 'same-origin'",
  "        });",
  "        var t = await r.text();",
  "        var doc = new DOMParser().parseFromString(t, 'text/html');",
  "        var heads = [];",
  "        var ths = doc.querySelectorAll('thead tr th');",
  "        for (var i = 0; i < ths.length; i++) { heads.push((ths[i].innerText || ths[i].textContent || '').trim()); }",
  "        var out = _gridReadTable(doc, heads, p);",
  "        var info = doc.querySelector('.admin__data-grid-info');",
  "        return JSON.stringify({",
  "            channel: 'legacy_ajax', namespace: (g.containerId || ''),",
  "            rows: out.rows, rows_returned: out.rows.length,",
  "            headers: heads, footer: out.footer,",
  "            info: info ? info.textContent.trim().slice(0, 80) : null,",
  "            applied: { sorting: p.sorting || null,",
  "                page_size: p.paging ? p.paging.pageSize : 200,",
  "                page: p.paging ? p.paging.current : 1 },",
  "            active_before: null, partial: false",
  "        });",
  "    } catch (e) { return JSON.stringify({channel_error: 'js-error: ' + e.message}); }",
  "})()",
  "",
].join("\n");

/** 纯 DOM <table> 解析通道（:628-683） */
export const DOM_TABLE_READ_JS = [
  "",
  "function _gridIsTotalLabel(s) {",
  "    var t = s.toLowerCase().trim();",
  "    // review2#1：'subtotal' 必须与 '小计' 对称——英文小计行不挪出 rows 会被",
  "    // column_sums 双计（Python 侧 _GRID_FOOTER_SKIP_LABELS 挪进 footer 后",
  "    // 按 'subtotal' 跳过比对）。",
  "    return t === 'total' || t === 'totals' || t === 'grand total'",
  "        || t === 'subtotal' || t === '合计' || t === '总计' || t === '小计';",
  "}",
  "function _gridReadRow(tr, heads, p) {",
  "    var cells = tr.querySelectorAll('td,th');",
  "    var row = {}, col = 0;",
  "    for (var c = 0; c < cells.length; c++) {",
  "        var key = (col < heads.length && heads[col]) ? heads[col] : ('col' + col);",
  "        // 注意：fields 过滤只跳过取值，列游标照常推进（被过滤的列仍占位）。",
  "        if (!(p.fields && p.fields.length && p.fields.indexOf(key) < 0)) {",
  "            row[key] = (cells[c].innerText || cells[c].textContent || '').trim();",
  "        }",
  "        // review#2：colspan 折算——合计行常见 <th colspan=N> 形态，按格索引",
  "        // 配对会把数值格绑到错误表头（假 ✗ 或相邻列合计恰等时假 ✓）。",
  "        col += (cells[c].colSpan || 1);",
  "    }",
  "    return row;",
  "}",
  "function _gridReadTable(root, heads, p) {",
  "    var rows = [], footer = [];",
  "    var trs = root.querySelectorAll('tbody tr');",
  "    for (var k = 0; k < trs.length; k++) {",
  "        if (!trs[k].querySelectorAll('td').length) { continue; }",
  "        // review#3：判定取首格（td,th）——合计标签写在 <th> 时首 td 是数值，",
  "        // 漏检会让 Total 行留在 rows 里被双计。",
  "        var cell0 = trs[k].querySelector('td,th');",
  "        var first = (cell0.innerText || cell0.textContent || '').trim();",
  "        if (_gridIsTotalLabel(first)) { footer.push(_gridReadRow(trs[k], heads, p)); continue; }",
  "        rows.push(_gridReadRow(trs[k], heads, p));",
  "    }",
  "    var ftrs = root.querySelectorAll('tfoot tr');",
  "    for (var f = 0; f < ftrs.length; f++) {",
  "        var fr = _gridReadRow(ftrs[f], heads, p);",
  "        if (Object.keys(fr).length) { footer.push(fr); }",
  "    }",
  "    return { rows: rows, footer: footer };",
  "}",
  "",
  "return (async function(){",
  "    var p = a[0];",
  "    try {",
  "        var tables = document.querySelectorAll('table');",
  "        var best = null, bestRows = 0;",
  "        for (var i = 0; i < tables.length; i++) {",
  "            var n = tables[i].querySelectorAll('tbody tr').length;",
  "            if (n > bestRows) { bestRows = n; best = tables[i]; }",
  "        }",
  "        if (!best || !bestRows) { return JSON.stringify({channel_error: 'no-table'}); }",
  "        var heads = [];",
  "        var ths = best.querySelectorAll('thead th');",
  "        for (var j = 0; j < ths.length; j++) { heads.push((ths[j].innerText || ths[j].textContent || '').trim()); }",
  "        var out = _gridReadTable(best, heads, p);",
  "        return JSON.stringify({",
  "            channel: 'dom_table', namespace: null, rows: out.rows, rows_returned: out.rows.length,",
  "            headers: heads, footer: out.footer,",
  "            applied: null, active_before: null, partial: false,",
  "            note: 'DOM channel: current-page visible rows only; no server-side sorting/paging'",
  "        });",
  "    } catch (e) { return JSON.stringify({channel_error: 'js-error: ' + e.message}); }",
  "})()",
  "",
].join("\n");

/** uiRegistry KO 网格主通道（session.py :3019-3113 类属性） */
export const GRID_READ_JS = [
  "",
  "return (async function(){",
  "    var p = a[0];",
  "    try {",
  "        if (typeof require !== 'function') { return JSON.stringify({channel_error: 'no-requirejs'}); }",
  "        var reg = await new Promise(function(r){ require(['uiRegistry'], r); });",
  "        var names = await new Promise(function(resolve){",
  "            var acc = [];",
  "            try { reg.get(function(c){ if (c && c.name) { acc.push(c.name); } return false; }); }",
  "            catch (e) {}",
  "            setTimeout(function(){ resolve(acc); }, 300);",
  "        });",
  "        var real = names.filter(function(n){ return n.indexOf('notification_area') !== 0; });",
  "        var ns = p.namespace || null;",
  "        if (!ns) {",
  "            for (var i = 0; i < real.length; i++) {",
  "                var n = real[i];",
  "                if (n.slice(-12) === '_data_source' && n.indexOf('.') === n.lastIndexOf('.')) {",
  "                    ns = n.split('.')[0]; break;",
  "                }",
  "            }",
  "        }",
  "        if (!ns) { return JSON.stringify({channel_error: 'no-grid', candidates: real.slice(0, 10)}); }",
  "        var ds = await new Promise(function(resolve){",
  "            var done = false;",
  "            reg.get(ns + '.' + ns + '_data_source', function(c){ done = true; resolve(c); });",
  "            setTimeout(function(){ if (!done) { resolve(null); } }, 1500);",
  "        });",
  "        if (!ds || !ds.data) { return JSON.stringify({channel_error: 'no-grid', namespace: ns}); }",
  "        function realFilters(f) {",
  "            var out = {};",
  "            f = f || {};",
  "            for (var k in f) {",
  "                if (k !== 'placeholder' && Object.prototype.hasOwnProperty.call(f, k)) { out[k] = f[k]; }",
  "            }",
  "            return out;",
  "        }",
  "        var activeBefore = {",
  "            filters: realFilters(ds.params && ds.params.filters),",
  "            search: (ds.params && ds.params.search) || '',",
  "            sorting: (ds.params && ds.params.sorting)",
  "                ? JSON.parse(JSON.stringify(ds.params.sorting)) : null",
  "        };",
  "        if (p.fresh) {",
  "            ds.set('params.filters', {placeholder: false});",
  "            ds.set('params.search', '');",
  "        }",
  "        if (p.filters) { ds.set('params.filters', Object.assign({placeholder: false}, p.filters)); }",
  "        if (typeof p.search === 'string' && p.search) { ds.set('params.search', p.search); }",
  "        if (p.sorting) { ds.set('params.sorting', p.sorting); }",
  "        if (p.paging) { ds.set('params.paging', p.paging); }",
  "        var reloaded = false;",
  "        try { if (typeof ds.reload === 'function') { ds.reload(); reloaded = true; } } catch (e) {}",
  "        try { ds.set('params.t', Date.now()); reloaded = true; } catch (e) {}",
  "        var stable = !reloaded;",
  "        if (reloaded) {",
  "            var last = '', stableCount = 0, t0 = Date.now();",
  "            while (Date.now() - t0 < (p.waitMs || 8000)) {",
  "                await new Promise(function(r){ setTimeout(r, 250); });",
  "                var d0 = ds.data || {};",
  "                var it0 = (d0.items instanceof Array) ? d0.items : [];",
  "                var cur = [d0.totalRecords || 0, it0.length,",
  "                    it0.length ? JSON.stringify(it0[0].entity_id || it0[0].id || '') : ''].join(':');",
  "                if (cur === last) { stableCount++; if (stableCount >= 2) { stable = true; break; } }",
  "                else { stableCount = 0; last = cur; }",
  "            }",
  "        }",
  "        var d = ds.data || {};",
  "        var items = (d.items instanceof Array) ? d.items : [];",
  "        var rows = items;",
  "        if (p.fields && p.fields.length) {",
  "            rows = items.map(function(it){",
  "                var r2 = {};",
  "                for (var j = 0; j < p.fields.length; j++) {",
  "                    var k = p.fields[j];",
  "                    if (it && Object.prototype.hasOwnProperty.call(it, k)) { r2[k] = it[k]; }",
  "                }",
  "                return r2;",
  "            });",
  "        }",
  "        return JSON.stringify({",
  "            channel: 'uiregistry', namespace: ns, rows: rows,",
  "            total_records: d.totalRecords,",
  "            applied: {",
  "                filters: realFilters(ds.params && ds.params.filters),",
  "                search: (ds.params && ds.params.search) || '',",
  "                sorting: (ds.params && ds.params.sorting) || null,",
  "                paging: (ds.params && ds.params.paging) || null",
  "            },",
  "            active_before: activeBefore, partial: !stable",
  "        });",
  "    } catch (e) { return JSON.stringify({channel_error: 'js-error: ' + e.message}); }",
  "})()",
  "",
].join("\n");
